# Generated by Django 2.2.3 on 2019-12-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20191203_1640'),
        ('parkinglot', '0006_auto_20191218_1147'),
        ('realtime', '0022_auto_20191217_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='', verbose_name='异常图片')),
                ('cam_id', models.CharField(max_length=100, null=True, verbose_name='camera_id(Mac地址)')),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='except_camera', to='device.Camera', verbose_name='摄像头')),
                ('gate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='except_gate', to='parkinglot.Gate', verbose_name='口')),
            ],
            options={
                'verbose_name': '异常记录',
                'verbose_name_plural': '异常记录',
            },
        ),
        migrations.AddField(
            model_name='inandout',
            name='exception',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtime.ExceptRecord', verbose_name='异常'),
        ),
    ]
